# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='hw',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
