# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_period_hw'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default='*', max_length=9),
        ),
    ]
