# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0006_auto_20170803_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='hw',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
