# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 03:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0007_auto_20170804_1121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Period',
        ),
    ]
