# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0008_delete_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='period',
            field=models.IntegerField(default=1),
        ),
    ]
