# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0012_auto_20170811_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='hw',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
