# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 11:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0014_homework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='log.Course'),
        ),
    ]
