# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 01:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0016_remove_course_hw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='code',
        ),
        migrations.RemoveField(
            model_name='course',
            name='period',
        ),
    ]
